function allcorrs = calFAA(secTime,lon,lat,filterlength)
    d2s = 24*3600;
    ndata = length(secTime);
    elipsoidheight=zeros(ndata,1);
    latCorr=-WGS84(lat)-FAC2ord(deg2rad(lat),elipsoidheight);
    Eotvos_Full=calc_eotvos_full(lat,lon,elipsoidheight,1);
    eCorr=Eotvos_Full'; % Eotvos full includes eotvos and vertical acceleration
    tideCorr=LongmanTidePredictor(lon,lat,secTime/d2s);
    [~,eCorrf] = gaussfilt(secTime,eCorr,filterlength);
    allcorrs = latCorr+eCorrf'+tideCorr;